apiVersion: v1
kind: Pod
metadata:
  name: k8s-app
  labels:
    app: k8s-app
spec:
  containers:
    - name: k8s-app
      image: mbinui/k8s-app:tagVersion
      ports:
        - containerPort: 8080
